service: sls-chat
frameworkVersion: '2'

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1
  lambdaHashingVersion: 20201221
  websocketsApiName: sls-chat-ws-api
  websocketsApiRouteSelectionExpression: $request.body.action
  environment:
    TABLE_NAME: sls-chat-connections

functions:
  connect:
    handler: src/connect.connect
    events:
      - websocket:
          route: $connect

resources:
  Resources:
    SimpleChatTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: simple_chatconnections
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1