service: sls-chat
frameworkVersion: '2'

custom:
  slsChatConnections: sls_chat_connections

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1
  lambdaHashingVersion: 20201221
  websocketsApiName: sls-chat-ws-api
  websocketsApiRouteSelectionExpression: $request.body.action
  environment:
    SLS_CHAT_CONNECTIONS: ${self:custom.slsChatConnections}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'dynamodb:PutItem'
        - 'dynamodb:GetItem'
        - 'dynamodb:DeleteItem'
        - 'dynamodb:Scan'
      Resource:
        - Fn::GetAtt: [SLSChatRoomConnectionsTable, Arn]
    - Effect: Allow
      Action:
        - 'execute-api:ManageConnections'
      Resource:
        - 'arn:aws:execute-api:*:*:**/@connections/*'

functions:
  connect:
    handler: src/connect.connect
    events:
      - websocket:
          route: $connect

resources:
  Resources:
    SLSChatRoomConnectionsTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:custom.slsChatConnections}
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1