service: aws-serverless
frameworkVersion: '2'

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: ap-northeast-1

functions:
  first:
    handler: first.hello
  second:
    handler: second.hello
    events:
      - httpApi:
          method: get
          path: /second
